/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSuppliersRouteImport } from './routes/_auth/suppliers'
import { Route as AuthStockAlertsRouteImport } from './routes/_auth/stock-alerts'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthReceiptsRouteImport } from './routes/_auth/receipts'
import { Route as AuthProspectingRouteImport } from './routes/_auth/prospecting'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthPosRouteImport } from './routes/_auth/pos'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthHrRouteImport } from './routes/_auth/hr'
import { Route as AuthHelperRouteImport } from './routes/_auth/helper'
import { Route as AuthExpensesRouteImport } from './routes/_auth/expenses'
import { Route as AuthDebtsRouteImport } from './routes/_auth/debts'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'
import { Route as AuthCategoriesRouteImport } from './routes/_auth/categories'
import { Route as AuthArchiveRouteImport } from './routes/_auth/archive'
import { Route as AuthSuppliersImportsRouteImport } from './routes/_auth/suppliers_.imports'
import { Route as AuthSuppliersSupplierIdRouteImport } from './routes/_auth/suppliers_.$supplierId'
import { Route as AuthReportsSalesRouteImport } from './routes/_auth/reports/sales'
import { Route as AuthReportsProfitRouteImport } from './routes/_auth/reports/profit'
import { Route as AuthProductsProductIdRouteImport } from './routes/_auth/products_.$productId'
import { Route as AuthDebtsCustomerIdRouteImport } from './routes/_auth/debts_.$customerId'
import { Route as AuthCustomersMapRouteImport } from './routes/_auth/customers_.map'
import { Route as AuthCustomersAddRouteImport } from './routes/_auth/customers_.add'
import { Route as AuthCustomersCustomerIdRouteImport } from './routes/_auth/customers_.$customerId'
import { Route as AuthSuppliersSupplierIdImportRouteImport } from './routes/_auth/suppliers_.$supplierId_.import'
import { Route as AuthCustomersCustomerIdLocationRouteImport } from './routes/_auth/customers_.$customerId_.location'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersRoute = AuthSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/suppliers.lazy').then((d) => d.Route),
)
const AuthStockAlertsRoute = AuthStockAlertsRouteImport.update({
  id: '/stock-alerts',
  path: '/stock-alerts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/settings.lazy').then((d) => d.Route),
)
const AuthReceiptsRoute = AuthReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProspectingRoute = AuthProspectingRouteImport.update({
  id: '/prospecting',
  path: '/prospecting',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/prospecting.lazy').then((d) => d.Route),
)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/products.lazy').then((d) => d.Route),
)
const AuthPosRoute = AuthPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/pos.lazy').then((d) => d.Route))
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrRoute = AuthHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/hr.lazy').then((d) => d.Route))
const AuthHelperRoute = AuthHelperRouteImport.update({
  id: '/helper',
  path: '/helper',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/helper.lazy').then((d) => d.Route))
const AuthExpensesRoute = AuthExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/expenses.lazy').then((d) => d.Route),
)
const AuthDebtsRoute = AuthDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/debts.lazy').then((d) => d.Route))
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/customers.lazy').then((d) => d.Route),
)
const AuthCategoriesRoute = AuthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/categories.lazy').then((d) => d.Route),
)
const AuthArchiveRoute = AuthArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSuppliersImportsRoute = AuthSuppliersImportsRouteImport.update({
  id: '/suppliers_/imports',
  path: '/suppliers/imports',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/suppliers_.imports.lazy').then((d) => d.Route),
)
const AuthSuppliersSupplierIdRoute = AuthSuppliersSupplierIdRouteImport.update({
  id: '/suppliers_/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/suppliers_.$supplierId.lazy').then((d) => d.Route),
)
const AuthReportsSalesRoute = AuthReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reports/sales.lazy').then((d) => d.Route),
)
const AuthReportsProfitRoute = AuthReportsProfitRouteImport.update({
  id: '/reports/profit',
  path: '/reports/profit',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reports/profit.lazy').then((d) => d.Route),
)
const AuthProductsProductIdRoute = AuthProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/products_.$productId.lazy').then((d) => d.Route),
)
const AuthDebtsCustomerIdRoute = AuthDebtsCustomerIdRouteImport.update({
  id: '/debts_/$customerId',
  path: '/debts/$customerId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/debts_.$customerId.lazy').then((d) => d.Route),
)
const AuthCustomersMapRoute = AuthCustomersMapRouteImport.update({
  id: '/customers_/map',
  path: '/customers/map',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/customers_.map.lazy').then((d) => d.Route),
)
const AuthCustomersAddRoute = AuthCustomersAddRouteImport.update({
  id: '/customers_/add',
  path: '/customers/add',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/customers_.add.lazy').then((d) => d.Route),
)
const AuthCustomersCustomerIdRoute = AuthCustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/customers_.$customerId.lazy').then((d) => d.Route),
)
const AuthSuppliersSupplierIdImportRoute =
  AuthSuppliersSupplierIdImportRouteImport.update({
    id: '/suppliers_/$supplierId_/import',
    path: '/suppliers/$supplierId/import',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/suppliers_.$supplierId_.import.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCustomersCustomerIdLocationRoute =
  AuthCustomersCustomerIdLocationRouteImport.update({
    id: '/customers_/$customerId_/location',
    path: '/customers/$customerId/location',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/customers_.$customerId_.location.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/archive': typeof AuthArchiveRoute
  '/categories': typeof AuthCategoriesRoute
  '/customers': typeof AuthCustomersRoute
  '/debts': typeof AuthDebtsRoute
  '/expenses': typeof AuthExpensesRoute
  '/helper': typeof AuthHelperRoute
  '/hr': typeof AuthHrRoute
  '/orders': typeof AuthOrdersRoute
  '/pos': typeof AuthPosRoute
  '/products': typeof AuthProductsRoute
  '/prospecting': typeof AuthProspectingRoute
  '/receipts': typeof AuthReceiptsRoute
  '/settings': typeof AuthSettingsRoute
  '/stock-alerts': typeof AuthStockAlertsRoute
  '/suppliers': typeof AuthSuppliersRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/customers/add': typeof AuthCustomersAddRoute
  '/customers/map': typeof AuthCustomersMapRoute
  '/debts/$customerId': typeof AuthDebtsCustomerIdRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/reports/profit': typeof AuthReportsProfitRoute
  '/reports/sales': typeof AuthReportsSalesRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/imports': typeof AuthSuppliersImportsRoute
  '/customers/$customerId/location': typeof AuthCustomersCustomerIdLocationRoute
  '/suppliers/$supplierId/import': typeof AuthSuppliersSupplierIdImportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/archive': typeof AuthArchiveRoute
  '/categories': typeof AuthCategoriesRoute
  '/customers': typeof AuthCustomersRoute
  '/debts': typeof AuthDebtsRoute
  '/expenses': typeof AuthExpensesRoute
  '/helper': typeof AuthHelperRoute
  '/hr': typeof AuthHrRoute
  '/orders': typeof AuthOrdersRoute
  '/pos': typeof AuthPosRoute
  '/products': typeof AuthProductsRoute
  '/prospecting': typeof AuthProspectingRoute
  '/receipts': typeof AuthReceiptsRoute
  '/settings': typeof AuthSettingsRoute
  '/stock-alerts': typeof AuthStockAlertsRoute
  '/suppliers': typeof AuthSuppliersRoute
  '/': typeof AuthIndexRoute
  '/customers/$customerId': typeof AuthCustomersCustomerIdRoute
  '/customers/add': typeof AuthCustomersAddRoute
  '/customers/map': typeof AuthCustomersMapRoute
  '/debts/$customerId': typeof AuthDebtsCustomerIdRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/reports/profit': typeof AuthReportsProfitRoute
  '/reports/sales': typeof AuthReportsSalesRoute
  '/suppliers/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/suppliers/imports': typeof AuthSuppliersImportsRoute
  '/customers/$customerId/location': typeof AuthCustomersCustomerIdLocationRoute
  '/suppliers/$supplierId/import': typeof AuthSuppliersSupplierIdImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/archive': typeof AuthArchiveRoute
  '/_auth/categories': typeof AuthCategoriesRoute
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/debts': typeof AuthDebtsRoute
  '/_auth/expenses': typeof AuthExpensesRoute
  '/_auth/helper': typeof AuthHelperRoute
  '/_auth/hr': typeof AuthHrRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/pos': typeof AuthPosRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/prospecting': typeof AuthProspectingRoute
  '/_auth/receipts': typeof AuthReceiptsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/stock-alerts': typeof AuthStockAlertsRoute
  '/_auth/suppliers': typeof AuthSuppliersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/customers_/$customerId': typeof AuthCustomersCustomerIdRoute
  '/_auth/customers_/add': typeof AuthCustomersAddRoute
  '/_auth/customers_/map': typeof AuthCustomersMapRoute
  '/_auth/debts_/$customerId': typeof AuthDebtsCustomerIdRoute
  '/_auth/products_/$productId': typeof AuthProductsProductIdRoute
  '/_auth/reports/profit': typeof AuthReportsProfitRoute
  '/_auth/reports/sales': typeof AuthReportsSalesRoute
  '/_auth/suppliers_/$supplierId': typeof AuthSuppliersSupplierIdRoute
  '/_auth/suppliers_/imports': typeof AuthSuppliersImportsRoute
  '/_auth/customers_/$customerId_/location': typeof AuthCustomersCustomerIdLocationRoute
  '/_auth/suppliers_/$supplierId_/import': typeof AuthSuppliersSupplierIdImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/archive'
    | '/categories'
    | '/customers'
    | '/debts'
    | '/expenses'
    | '/helper'
    | '/hr'
    | '/orders'
    | '/pos'
    | '/products'
    | '/prospecting'
    | '/receipts'
    | '/settings'
    | '/stock-alerts'
    | '/suppliers'
    | '/customers/$customerId'
    | '/customers/add'
    | '/customers/map'
    | '/debts/$customerId'
    | '/products/$productId'
    | '/reports/profit'
    | '/reports/sales'
    | '/suppliers/$supplierId'
    | '/suppliers/imports'
    | '/customers/$customerId/location'
    | '/suppliers/$supplierId/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/archive'
    | '/categories'
    | '/customers'
    | '/debts'
    | '/expenses'
    | '/helper'
    | '/hr'
    | '/orders'
    | '/pos'
    | '/products'
    | '/prospecting'
    | '/receipts'
    | '/settings'
    | '/stock-alerts'
    | '/suppliers'
    | '/'
    | '/customers/$customerId'
    | '/customers/add'
    | '/customers/map'
    | '/debts/$customerId'
    | '/products/$productId'
    | '/reports/profit'
    | '/reports/sales'
    | '/suppliers/$supplierId'
    | '/suppliers/imports'
    | '/customers/$customerId/location'
    | '/suppliers/$supplierId/import'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/archive'
    | '/_auth/categories'
    | '/_auth/customers'
    | '/_auth/debts'
    | '/_auth/expenses'
    | '/_auth/helper'
    | '/_auth/hr'
    | '/_auth/orders'
    | '/_auth/pos'
    | '/_auth/products'
    | '/_auth/prospecting'
    | '/_auth/receipts'
    | '/_auth/settings'
    | '/_auth/stock-alerts'
    | '/_auth/suppliers'
    | '/_auth/'
    | '/_auth/customers_/$customerId'
    | '/_auth/customers_/add'
    | '/_auth/customers_/map'
    | '/_auth/debts_/$customerId'
    | '/_auth/products_/$productId'
    | '/_auth/reports/profit'
    | '/_auth/reports/sales'
    | '/_auth/suppliers_/$supplierId'
    | '/_auth/suppliers_/imports'
    | '/_auth/customers_/$customerId_/location'
    | '/_auth/suppliers_/$supplierId_/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers': {
      id: '/_auth/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthSuppliersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stock-alerts': {
      id: '/_auth/stock-alerts'
      path: '/stock-alerts'
      fullPath: '/stock-alerts'
      preLoaderRoute: typeof AuthStockAlertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/receipts': {
      id: '/_auth/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthReceiptsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/prospecting': {
      id: '/_auth/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof AuthProspectingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pos': {
      id: '/_auth/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthPosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr': {
      id: '/_auth/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthHrRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/helper': {
      id: '/_auth/helper'
      path: '/helper'
      fullPath: '/helper'
      preLoaderRoute: typeof AuthHelperRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/expenses': {
      id: '/_auth/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthExpensesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/debts': {
      id: '/_auth/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthDebtsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories': {
      id: '/_auth/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/archive': {
      id: '/_auth/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthArchiveRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers_/imports': {
      id: '/_auth/suppliers_/imports'
      path: '/suppliers/imports'
      fullPath: '/suppliers/imports'
      preLoaderRoute: typeof AuthSuppliersImportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers_/$supplierId': {
      id: '/_auth/suppliers_/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/sales': {
      id: '/_auth/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthReportsSalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/profit': {
      id: '/_auth/reports/profit'
      path: '/reports/profit'
      fullPath: '/reports/profit'
      preLoaderRoute: typeof AuthReportsProfitRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/$productId': {
      id: '/_auth/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthProductsProductIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/debts_/$customerId': {
      id: '/_auth/debts_/$customerId'
      path: '/debts/$customerId'
      fullPath: '/debts/$customerId'
      preLoaderRoute: typeof AuthDebtsCustomerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers_/map': {
      id: '/_auth/customers_/map'
      path: '/customers/map'
      fullPath: '/customers/map'
      preLoaderRoute: typeof AuthCustomersMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers_/add': {
      id: '/_auth/customers_/add'
      path: '/customers/add'
      fullPath: '/customers/add'
      preLoaderRoute: typeof AuthCustomersAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers_/$customerId': {
      id: '/_auth/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthCustomersCustomerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers_/$supplierId_/import': {
      id: '/_auth/suppliers_/$supplierId_/import'
      path: '/suppliers/$supplierId/import'
      fullPath: '/suppliers/$supplierId/import'
      preLoaderRoute: typeof AuthSuppliersSupplierIdImportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers_/$customerId_/location': {
      id: '/_auth/customers_/$customerId_/location'
      path: '/customers/$customerId/location'
      fullPath: '/customers/$customerId/location'
      preLoaderRoute: typeof AuthCustomersCustomerIdLocationRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthArchiveRoute: typeof AuthArchiveRoute
  AuthCategoriesRoute: typeof AuthCategoriesRoute
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDebtsRoute: typeof AuthDebtsRoute
  AuthExpensesRoute: typeof AuthExpensesRoute
  AuthHelperRoute: typeof AuthHelperRoute
  AuthHrRoute: typeof AuthHrRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthPosRoute: typeof AuthPosRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthProspectingRoute: typeof AuthProspectingRoute
  AuthReceiptsRoute: typeof AuthReceiptsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthStockAlertsRoute: typeof AuthStockAlertsRoute
  AuthSuppliersRoute: typeof AuthSuppliersRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCustomersCustomerIdRoute: typeof AuthCustomersCustomerIdRoute
  AuthCustomersAddRoute: typeof AuthCustomersAddRoute
  AuthCustomersMapRoute: typeof AuthCustomersMapRoute
  AuthDebtsCustomerIdRoute: typeof AuthDebtsCustomerIdRoute
  AuthProductsProductIdRoute: typeof AuthProductsProductIdRoute
  AuthReportsProfitRoute: typeof AuthReportsProfitRoute
  AuthReportsSalesRoute: typeof AuthReportsSalesRoute
  AuthSuppliersSupplierIdRoute: typeof AuthSuppliersSupplierIdRoute
  AuthSuppliersImportsRoute: typeof AuthSuppliersImportsRoute
  AuthCustomersCustomerIdLocationRoute: typeof AuthCustomersCustomerIdLocationRoute
  AuthSuppliersSupplierIdImportRoute: typeof AuthSuppliersSupplierIdImportRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArchiveRoute: AuthArchiveRoute,
  AuthCategoriesRoute: AuthCategoriesRoute,
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDebtsRoute: AuthDebtsRoute,
  AuthExpensesRoute: AuthExpensesRoute,
  AuthHelperRoute: AuthHelperRoute,
  AuthHrRoute: AuthHrRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthPosRoute: AuthPosRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthProspectingRoute: AuthProspectingRoute,
  AuthReceiptsRoute: AuthReceiptsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthStockAlertsRoute: AuthStockAlertsRoute,
  AuthSuppliersRoute: AuthSuppliersRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthCustomersCustomerIdRoute: AuthCustomersCustomerIdRoute,
  AuthCustomersAddRoute: AuthCustomersAddRoute,
  AuthCustomersMapRoute: AuthCustomersMapRoute,
  AuthDebtsCustomerIdRoute: AuthDebtsCustomerIdRoute,
  AuthProductsProductIdRoute: AuthProductsProductIdRoute,
  AuthReportsProfitRoute: AuthReportsProfitRoute,
  AuthReportsSalesRoute: AuthReportsSalesRoute,
  AuthSuppliersSupplierIdRoute: AuthSuppliersSupplierIdRoute,
  AuthSuppliersImportsRoute: AuthSuppliersImportsRoute,
  AuthCustomersCustomerIdLocationRoute: AuthCustomersCustomerIdLocationRoute,
  AuthSuppliersSupplierIdImportRoute: AuthSuppliersSupplierIdImportRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
