/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthWarehouseRouteImport } from './routes/_auth/warehouse'
import { Route as AuthSuppliersRouteImport } from './routes/_auth/suppliers'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthPosRouteImport } from './routes/_auth/pos'
import { Route as AuthPartnersRouteImport } from './routes/_auth/partners'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthMonitoringRouteImport } from './routes/_auth/monitoring'
import { Route as AuthHrRouteImport } from './routes/_auth/hr'
import { Route as AuthExpensesRouteImport } from './routes/_auth/expenses'
import { Route as AuthDebtsRouteImport } from './routes/_auth/debts'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'
import { Route as AuthContactsRouteImport } from './routes/_auth/contacts'
import { Route as AuthCategoriesRouteImport } from './routes/_auth/categories'
import { Route as AuthReportsSalesRouteImport } from './routes/_auth/reports/sales'
import { Route as AuthReportsProfitRouteImport } from './routes/_auth/reports/profit'
import { Route as AuthProductsProductIdRouteImport } from './routes/_auth/products_.$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWarehouseRoute = AuthWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/warehouse.lazy').then((d) => d.Route),
)
const AuthSuppliersRoute = AuthSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/suppliers.lazy').then((d) => d.Route),
)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/settings.lazy').then((d) => d.Route),
)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/products.lazy').then((d) => d.Route),
)
const AuthPosRoute = AuthPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/pos.lazy').then((d) => d.Route))
const AuthPartnersRoute = AuthPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/partners.lazy').then((d) => d.Route),
)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/orders.lazy').then((d) => d.Route))
const AuthMonitoringRoute = AuthMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/monitoring.lazy').then((d) => d.Route),
)
const AuthHrRoute = AuthHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/hr.lazy').then((d) => d.Route))
const AuthExpensesRoute = AuthExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/expenses.lazy').then((d) => d.Route),
)
const AuthDebtsRoute = AuthDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/debts.lazy').then((d) => d.Route))
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/customers.lazy').then((d) => d.Route),
)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/contacts.lazy').then((d) => d.Route),
)
const AuthCategoriesRoute = AuthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/categories.lazy').then((d) => d.Route),
)
const AuthReportsSalesRoute = AuthReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reports/sales.lazy').then((d) => d.Route),
)
const AuthReportsProfitRoute = AuthReportsProfitRouteImport.update({
  id: '/reports/profit',
  path: '/reports/profit',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reports/profit.lazy').then((d) => d.Route),
)
const AuthProductsProductIdRoute = AuthProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/products_.$productId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthCategoriesRoute
  '/contacts': typeof AuthContactsRoute
  '/customers': typeof AuthCustomersRoute
  '/debts': typeof AuthDebtsRoute
  '/expenses': typeof AuthExpensesRoute
  '/hr': typeof AuthHrRoute
  '/monitoring': typeof AuthMonitoringRoute
  '/orders': typeof AuthOrdersRoute
  '/partners': typeof AuthPartnersRoute
  '/pos': typeof AuthPosRoute
  '/products': typeof AuthProductsRoute
  '/settings': typeof AuthSettingsRoute
  '/suppliers': typeof AuthSuppliersRoute
  '/warehouse': typeof AuthWarehouseRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/reports/profit': typeof AuthReportsProfitRoute
  '/reports/sales': typeof AuthReportsSalesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categories': typeof AuthCategoriesRoute
  '/contacts': typeof AuthContactsRoute
  '/customers': typeof AuthCustomersRoute
  '/debts': typeof AuthDebtsRoute
  '/expenses': typeof AuthExpensesRoute
  '/hr': typeof AuthHrRoute
  '/monitoring': typeof AuthMonitoringRoute
  '/orders': typeof AuthOrdersRoute
  '/partners': typeof AuthPartnersRoute
  '/pos': typeof AuthPosRoute
  '/products': typeof AuthProductsRoute
  '/settings': typeof AuthSettingsRoute
  '/suppliers': typeof AuthSuppliersRoute
  '/warehouse': typeof AuthWarehouseRoute
  '/': typeof AuthIndexRoute
  '/products/$productId': typeof AuthProductsProductIdRoute
  '/reports/profit': typeof AuthReportsProfitRoute
  '/reports/sales': typeof AuthReportsSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/categories': typeof AuthCategoriesRoute
  '/_auth/contacts': typeof AuthContactsRoute
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/debts': typeof AuthDebtsRoute
  '/_auth/expenses': typeof AuthExpensesRoute
  '/_auth/hr': typeof AuthHrRoute
  '/_auth/monitoring': typeof AuthMonitoringRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/partners': typeof AuthPartnersRoute
  '/_auth/pos': typeof AuthPosRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/suppliers': typeof AuthSuppliersRoute
  '/_auth/warehouse': typeof AuthWarehouseRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/products_/$productId': typeof AuthProductsProductIdRoute
  '/_auth/reports/profit': typeof AuthReportsProfitRoute
  '/_auth/reports/sales': typeof AuthReportsSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/contacts'
    | '/customers'
    | '/debts'
    | '/expenses'
    | '/hr'
    | '/monitoring'
    | '/orders'
    | '/partners'
    | '/pos'
    | '/products'
    | '/settings'
    | '/suppliers'
    | '/warehouse'
    | '/products/$productId'
    | '/reports/profit'
    | '/reports/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categories'
    | '/contacts'
    | '/customers'
    | '/debts'
    | '/expenses'
    | '/hr'
    | '/monitoring'
    | '/orders'
    | '/partners'
    | '/pos'
    | '/products'
    | '/settings'
    | '/suppliers'
    | '/warehouse'
    | '/'
    | '/products/$productId'
    | '/reports/profit'
    | '/reports/sales'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/categories'
    | '/_auth/contacts'
    | '/_auth/customers'
    | '/_auth/debts'
    | '/_auth/expenses'
    | '/_auth/hr'
    | '/_auth/monitoring'
    | '/_auth/orders'
    | '/_auth/partners'
    | '/_auth/pos'
    | '/_auth/products'
    | '/_auth/settings'
    | '/_auth/suppliers'
    | '/_auth/warehouse'
    | '/_auth/'
    | '/_auth/products_/$productId'
    | '/_auth/reports/profit'
    | '/_auth/reports/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/warehouse': {
      id: '/_auth/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthWarehouseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/suppliers': {
      id: '/_auth/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthSuppliersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pos': {
      id: '/_auth/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthPosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/partners': {
      id: '/_auth/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthPartnersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitoring': {
      id: '/_auth/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthMonitoringRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr': {
      id: '/_auth/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthHrRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/expenses': {
      id: '/_auth/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthExpensesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/debts': {
      id: '/_auth/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AuthDebtsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories': {
      id: '/_auth/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/sales': {
      id: '/_auth/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthReportsSalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/profit': {
      id: '/_auth/reports/profit'
      path: '/reports/profit'
      fullPath: '/reports/profit'
      preLoaderRoute: typeof AuthReportsProfitRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products_/$productId': {
      id: '/_auth/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthProductsProductIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCategoriesRoute: typeof AuthCategoriesRoute
  AuthContactsRoute: typeof AuthContactsRoute
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDebtsRoute: typeof AuthDebtsRoute
  AuthExpensesRoute: typeof AuthExpensesRoute
  AuthHrRoute: typeof AuthHrRoute
  AuthMonitoringRoute: typeof AuthMonitoringRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthPartnersRoute: typeof AuthPartnersRoute
  AuthPosRoute: typeof AuthPosRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSuppliersRoute: typeof AuthSuppliersRoute
  AuthWarehouseRoute: typeof AuthWarehouseRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthProductsProductIdRoute: typeof AuthProductsProductIdRoute
  AuthReportsProfitRoute: typeof AuthReportsProfitRoute
  AuthReportsSalesRoute: typeof AuthReportsSalesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCategoriesRoute: AuthCategoriesRoute,
  AuthContactsRoute: AuthContactsRoute,
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDebtsRoute: AuthDebtsRoute,
  AuthExpensesRoute: AuthExpensesRoute,
  AuthHrRoute: AuthHrRoute,
  AuthMonitoringRoute: AuthMonitoringRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthPartnersRoute: AuthPartnersRoute,
  AuthPosRoute: AuthPosRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSuppliersRoute: AuthSuppliersRoute,
  AuthWarehouseRoute: AuthWarehouseRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthProductsProductIdRoute: AuthProductsProductIdRoute,
  AuthReportsProfitRoute: AuthReportsProfitRoute,
  AuthReportsSalesRoute: AuthReportsSalesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
